### ISSUE TITLE
Info about transducer implementation

### ISSUE THREAD

**Issue by giuliohome** [bmurphy1976/transducers-dotnet#1]
Nice work! 
Thank you for sharing! 

Can I say that this corresponds to the JavaScript transducer  explained in [this blog](http://raganwald.com/2017/04/30/transducers.html)?
I 'd like to port that example to C# and then use the transducer instead of Linq in .net to get better performance and write functional code.

I've also opened a [JS bounty question on SO](http://stackoverflow.com/questions/44022945/function-composition-with-rest-operator-reducer-and-mapper/) and I guess the C# version could easily overcome any ecmascript 6 limitations...

By the way, this is a [gist with C# porting](https://gist.github.com/giuliohome/fe082cdd508a12c877709e1134685ed9)

**Comment by bmurphy1976** [comment]
I wrote this years ago and I don't remember any of the specifics.  When I wrote it I wasn't trying to solve any problem, I was merely trying to prove to myself I understood the concept.

Unfortunately I can't honestly answer your question because I'm so far removed from this these days.  I've lost all context.

That said, I strongly recommend, if you do this, do it for the learning experience and stop there.  If you use transducers in production C# code you are only going to create issues for yourself down the road.  The benefit of using a hacky Transducers implementation over a the very thoroughly proven and well tested Linq/Collections APIs built into the .NET framework are not justifiable.

**Comment by giuliohome** [comment]
No worries, when I move _my_ code to Production, the buck stops here at _my_ desk. I know how to read and adapt a few lines of code and btw Linq is _not_ a replacement for transducers, etc... Thanks anyway, your message is a safe advice for others.

**Comment by bmurphy1976** [comment]
Best of luck!
